services:
  child-vue3-enterprise-mongo:
    image: mongo:latest
    container_name: child-vue3-enterprise-mongo
    volumes:
      - '.docker-volumes/mongo/data:/data/db'
    ports:
      - 27017:27017
  child-vue3-enterprise:
    depends_on:
      - child-vue3-enterprise-mongo
    build:
      context: . # 当前目录
      dockerfile: Dockerfile # 基于 Dockerfile 构建
    image: micro-app-child-enterprise
    container_name: child-vue3-enterprise
    ports:
      - "8080:80"
    